package com.fren_gor.ultimateAdvancementAPI.tests.database;

public enum DBOperation {
    GET_TEAM_ID,
    GET_TEAM_MEMBERS,
    GET_TEAM_ADVANCEMENTS,
    LOAD_OR_REGISTER_PLAYER,
    LOAD_UUID,
    CREATE_NEW_TEAM,
    LOAD_TEAM,
    UPDATE_ADVANCEMENT,
    GET_UNREDEEMED,
    SET_UNREDEEMED,
    IS_UNREDEEMED,
    UNSET_UNREDEEMED,
    UNREGISTER_PLAYER,
    MOVE_PLAYER,
    MOVE_PLAYER_IN_NEW_TEAM,
    GET_PLAYERS_BY_NAME,
    GET_PLAYER_NAME,
    UPDATE_PLAYER_NAME,
    SET_TEAM_PERMANENT,
    IS_TEAM_PERMANENT,
    GET_PERMANENT_TEAMS,
    CLEAR_UP_TEAMS;
}
